/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SenseHatApi);
  }
}(this, function(expect, SenseHatApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SenseHatApi.EnvironmentalSensorApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EnvironmentalSensorApi', function() {
    describe('environmentalSensorsGetHumidityGet', function() {
      it('should call environmentalSensorsGetHumidityGet successfully', function(done) {
        //uncomment below and update the code to test environmentalSensorsGetHumidityGet
        //instance.environmentalSensorsGetHumidityGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('environmentalSensorsGetPressureGet', function() {
      it('should call environmentalSensorsGetPressureGet successfully', function(done) {
        //uncomment below and update the code to test environmentalSensorsGetPressureGet
        //instance.environmentalSensorsGetPressureGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('environmentalSensorsGetTemperatureFromHumidityGet', function() {
      it('should call environmentalSensorsGetTemperatureFromHumidityGet successfully', function(done) {
        //uncomment below and update the code to test environmentalSensorsGetTemperatureFromHumidityGet
        //instance.environmentalSensorsGetTemperatureFromHumidityGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('environmentalSensorsGetTemperatureFromPressureGet', function() {
      it('should call environmentalSensorsGetTemperatureFromPressureGet successfully', function(done) {
        //uncomment below and update the code to test environmentalSensorsGetTemperatureFromPressureGet
        //instance.environmentalSensorsGetTemperatureFromPressureGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('environmentalSensorsGetTemperatureGet', function() {
      it('should call environmentalSensorsGetTemperatureGet successfully', function(done) {
        //uncomment below and update the code to test environmentalSensorsGetTemperatureGet
        //instance.environmentalSensorsGetTemperatureGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
