/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SenseHatApi);
  }
}(this, function(expect, SenseHatApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SenseHatApi.LEDApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LEDApi', function() {
    describe('lEDMatrixClearPut', function() {
      it('should call lEDMatrixClearPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixClearPut
        //instance.lEDMatrixClearPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixFlipHPut', function() {
      it('should call lEDMatrixFlipHPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixFlipHPut
        //instance.lEDMatrixFlipHPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixFlipVPut', function() {
      it('should call lEDMatrixFlipVPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixFlipVPut
        //instance.lEDMatrixFlipVPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixGetPixelGet', function() {
      it('should call lEDMatrixGetPixelGet successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixGetPixelGet
        //instance.lEDMatrixGetPixelGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixGetPixelsGet', function() {
      it('should call lEDMatrixGetPixelsGet successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixGetPixelsGet
        //instance.lEDMatrixGetPixelsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixLowLightPut', function() {
      it('should call lEDMatrixLowLightPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixLowLightPut
        //instance.lEDMatrixLowLightPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixSetPixelPut', function() {
      it('should call lEDMatrixSetPixelPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixSetPixelPut
        //instance.lEDMatrixSetPixelPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixSetPixelsPut', function() {
      it('should call lEDMatrixSetPixelsPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixSetPixelsPut
        //instance.lEDMatrixSetPixelsPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixSetRotationPut', function() {
      it('should call lEDMatrixSetRotationPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixSetRotationPut
        //instance.lEDMatrixSetRotationPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixShowLetterPut', function() {
      it('should call lEDMatrixShowLetterPut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixShowLetterPut
        //instance.lEDMatrixShowLetterPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lEDMatrixShowMessagePut', function() {
      it('should call lEDMatrixShowMessagePut successfully', function(done) {
        //uncomment below and update the code to test lEDMatrixShowMessagePut
        //instance.lEDMatrixShowMessagePut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
