/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SenseHatApi) {
      root.SenseHatApi = {};
    }
    root.SenseHatApi.Colour = factory(root.SenseHatApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Colour model module.
   * @module model/Colour
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Colour</code>.
   * @alias module:model/Colour
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Colour</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Colour} obj Optional instance to populate.
   * @return {module:model/Colour} The populated <code>Colour</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('red')) {
        obj['red'] = ApiClient.convertToType(data['red'], 'Number');
      }
      if (data.hasOwnProperty('green')) {
        obj['green'] = ApiClient.convertToType(data['green'], 'Number');
      }
      if (data.hasOwnProperty('blue')) {
        obj['blue'] = ApiClient.convertToType(data['blue'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The Red element of the colour.
   * @member {Number} red
   */
  exports.prototype['red'] = undefined;
  /**
   * The Green element of the colour.
   * @member {Number} green
   */
  exports.prototype['green'] = undefined;
  /**
   * The Blue element of the colour.
   * @member {Number} blue
   */
  exports.prototype['blue'] = undefined;



  return exports;
}));


