/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SenseHatApi) {
      root.SenseHatApi = {};
    }
    root.SenseHatApi.Orientation = factory(root.SenseHatApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Orientation model module.
   * @module model/Orientation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Orientation</code>.
   * @alias module:model/Orientation
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Orientation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Orientation} obj Optional instance to populate.
   * @return {module:model/Orientation} The populated <code>Orientation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pitch')) {
        obj['pitch'] = ApiClient.convertToType(data['pitch'], 'Number');
      }
      if (data.hasOwnProperty('roll')) {
        obj['roll'] = ApiClient.convertToType(data['roll'], 'Number');
      }
      if (data.hasOwnProperty('yaw')) {
        obj['yaw'] = ApiClient.convertToType(data['yaw'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The pitch.
   * @member {Number} pitch
   */
  exports.prototype['pitch'] = undefined;
  /**
   * The roll.
   * @member {Number} roll
   */
  exports.prototype['roll'] = undefined;
  /**
   * The yaw.
   * @member {Number} yaw
   */
  exports.prototype['yaw'] = undefined;



  return exports;
}));


