/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Colour'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Colour'));
  } else {
    // Browser globals (root is window)
    if (!root.SenseHatApi) {
      root.SenseHatApi = {};
    }
    root.SenseHatApi.Pixel = factory(root.SenseHatApi.ApiClient, root.SenseHatApi.Colour);
  }
}(this, function(ApiClient, Colour) {
  'use strict';




  /**
   * The Pixel model module.
   * @module model/Pixel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Pixel</code>.
   * @alias module:model/Pixel
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Pixel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pixel} obj Optional instance to populate.
   * @return {module:model/Pixel} The populated <code>Pixel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('x')) {
        obj['x'] = ApiClient.convertToType(data['x'], 'Number');
      }
      if (data.hasOwnProperty('y')) {
        obj['y'] = ApiClient.convertToType(data['y'], 'Number');
      }
      if (data.hasOwnProperty('colour')) {
        obj['colour'] = Colour.constructFromObject(data['colour']);
      }
    }
    return obj;
  }

  /**
   * 0 is on the left, 7 on the right.
   * @member {Number} x
   */
  exports.prototype['x'] = undefined;
  /**
   * 0 is at the top, 7 at the bottom.
   * @member {Number} y
   */
  exports.prototype['y'] = undefined;
  /**
   * @member {module:model/Colour} colour
   */
  exports.prototype['colour'] = undefined;



  return exports;
}));


