/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SenseHatApi) {
      root.SenseHatApi = {};
    }
    root.SenseHatApi.Vertice = factory(root.SenseHatApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Vertice model module.
   * @module model/Vertice
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Vertice</code>.
   * @alias module:model/Vertice
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Vertice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vertice} obj Optional instance to populate.
   * @return {module:model/Vertice} The populated <code>Vertice</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('x')) {
        obj['x'] = ApiClient.convertToType(data['x'], 'Number');
      }
      if (data.hasOwnProperty('y')) {
        obj['y'] = ApiClient.convertToType(data['y'], 'Number');
      }
      if (data.hasOwnProperty('z')) {
        obj['z'] = ApiClient.convertToType(data['z'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The x.
   * @member {Number} x
   */
  exports.prototype['x'] = undefined;
  /**
   * The y.
   * @member {Number} y
   */
  exports.prototype['y'] = undefined;
  /**
   * The z.
   * @member {Number} z
   */
  exports.prototype['z'] = undefined;



  return exports;
}));


