/* 
 * Sense HAT API
 *
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Vertice
    /// </summary>
    [DataContract]
    public partial class Vertice :  IEquatable<Vertice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Vertice" /> class.
        /// </summary>
        /// <param name="X">The x..</param>
        /// <param name="Y">The y..</param>
        /// <param name="Z">The z..</param>
        public Vertice(decimal? X = default(decimal?), decimal? Y = default(decimal?), decimal? Z = default(decimal?))
        {
            this.X = X;
            this.Y = Y;
            this.Z = Z;
        }
        
        /// <summary>
        /// The x.
        /// </summary>
        /// <value>The x.</value>
        [DataMember(Name="x", EmitDefaultValue=false)]
        public decimal? X { get; set; }
        /// <summary>
        /// The y.
        /// </summary>
        /// <value>The y.</value>
        [DataMember(Name="y", EmitDefaultValue=false)]
        public decimal? Y { get; set; }
        /// <summary>
        /// The z.
        /// </summary>
        /// <value>The z.</value>
        [DataMember(Name="z", EmitDefaultValue=false)]
        public decimal? Z { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Vertice {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Vertice);
        }

        /// <summary>
        /// Returns true if Vertice instances are equal
        /// </summary>
        /// <param name="other">Instance of Vertice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Vertice other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.X == other.X ||
                    this.X != null &&
                    this.X.Equals(other.X)
                ) && 
                (
                    this.Y == other.Y ||
                    this.Y != null &&
                    this.Y.Equals(other.Y)
                ) && 
                (
                    this.Z == other.Z ||
                    this.Z != null &&
                    this.Z.Equals(other.Z)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.X != null)
                    hash = hash * 59 + this.X.GetHashCode();
                if (this.Y != null)
                    hash = hash * 59 + this.Y.GetHashCode();
                if (this.Z != null)
                    hash = hash * 59 + this.Z.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
