/* 
 * Sense HAT API
 *
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Orientation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrientationTests
    {
        // TODO uncomment below to declare an instance variable for Orientation
        //private Orientation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Orientation
            //instance = new Orientation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Orientation
        /// </summary>
        [Test]
        public void OrientationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Orientation
            //Assert.IsInstanceOfType<Orientation> (instance, "variable 'instance' is a Orientation");
        }

        /// <summary>
        /// Test the property 'Pitch'
        /// </summary>
        [Test]
        public void PitchTest()
        {
            // TODO unit test for the property 'Pitch'
        }
        /// <summary>
        /// Test the property 'Roll'
        /// </summary>
        [Test]
        public void RollTest()
        {
            // TODO unit test for the property 'Roll'
        }
        /// <summary>
        /// Test the property 'Yaw'
        /// </summary>
        [Test]
        public void YawTest()
        {
            // TODO unit test for the property 'Yaw'
        }

    }

}
