/**
 * Sense HAT API
 * Sense HAT API Express wrapper (http://pythonhosted.org/sense-hat/api/#sense-hat-api-reference).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SenseHatApi);
  }
}(this, function(expect, SenseHatApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SenseHatApi.Orientation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Orientation', function() {
    it('should create an instance of Orientation', function() {
      // uncomment below and update the code to test Orientation
      //var instane = new SenseHatApi.Orientation();
      //expect(instance).to.be.a(SenseHatApi.Orientation);
    });

    it('should have the property pitch (base name: "pitch")', function() {
      // uncomment below and update the code to test the property pitch
      //var instane = new SenseHatApi.Orientation();
      //expect(instance).to.be();
    });

    it('should have the property roll (base name: "roll")', function() {
      // uncomment below and update the code to test the property roll
      //var instane = new SenseHatApi.Orientation();
      //expect(instance).to.be();
    });

    it('should have the property yaw (base name: "yaw")', function() {
      // uncomment below and update the code to test the property yaw
      //var instane = new SenseHatApi.Orientation();
      //expect(instance).to.be();
    });

  });

}));
